spring:
  application:
    name: uuid-server
  redis: # redis配置 ========================
    host: 172.16.10.106
    port: 6379
    timeout: 5000ms
server:
  port: 8082

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://uuid-eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
  instance:
    hostname: uuid-server

uuid:
  # ID生成器的应用名称
  client-application-name: uuid-snowflake-client
  # 机器数量，默认2台，最大31*31=961台
  machine-count: 10
  # 同步检测已使用池中的数据和eureka注册表中的实例数30秒，生产环境设置10分钟以上
  task-execution-interval: 30
