apiVersion: v1
kind: Service
metadata:
  name: uuid-eureka-server
  labels:
    app: uuid-eureka-server
spec:
  ports:
  - port: 8761
    name: http
    protocol: TCP
    targetPort: 8761
  type: NodePort
  selector:
    app: uuid-eureka-server

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: uuid-eureka-server
spec:
  selector:
    matchLabels:
      app: uuid-eureka-server
  serviceName: "uuid-eureka-server"
  replicas: 3
  template:
    metadata:
      labels:
        app: uuid-eureka-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: uuid-eureka-server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: test
        - name: ADDITIONAL_EUREKA_SERVER_LIST
          #value: "http://eureka-server:8761/eureka"
          value: "http://uuid-eureka-server-0.uuid-eureka-server.default.svc.cluster.local:8761/eureka,http://uuid-eureka-server-1.uuid-eureka-server.default.svc.cluster.local:8761/eureka,http://uuid-eureka-server-2.uuid-eureka-server.default.svc.cluster.local:8761/eureka"
        image:  172.16.10.192:5000/bobo/uuid-eureka-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
          protocol: TCP
      imagePullSecrets:
      - name: dockercfg-192
