apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: uuid-server
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: uuid-server
    spec:
      containers:
      - name: uuid-server
        image: 172.16.10.192:5000/bobo/uuid-server:latest
        ports:
        - containerPort: 8082
      imagePullSecrets:
        - name: dockercfg-192

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: uuid-snowflake-client
spec:
  replicas: 3 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: uuid-snowflake-client
    spec:
      containers:
      - name: uuid-snowflake-client
        image: 172.16.10.192:5000/bobo/uuid-snowflake-client:latest
        ports:
        - containerPort: 8123
      imagePullSecrets:
        - name: dockercfg-192

---
apiVersion: v1
kind: Service
metadata:
  name: uuid-snowflake-client
  labels:
    app: uuid-snowflake-client
spec:
  type: NodePort
  selector:
    app: uuid-snowflake-client
  ports:
  - name: http
    port: 8123
    targetPort: 8123