spring:
  application:
    name: uuid-snowflake-client
  redis: # redis配置 ========================
    host: localhost
    port: 6379
    timeout: 5000ms
server:
  port: 8123

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    # 如果是集群模式部署，instance-id值必须设置
    instance-id: ${spring.application.name}:${server.port}:${random.int}

  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
